import html
import os
import requests
from .base import Tool


def _get_from_email() -> str:
    """Configurable sender address; falls back to Resend's sandbox domain."""
    return os.getenv("RESEND_FROM_EMAIL", "onboarding@resend.dev")


class EmailTool(Tool):
    name = "email"
    description = "Send the travel briefing email via Resend."

    def __init__(self, api_key):
        self.api_key = api_key

    def run(self, to, subject, body):
        if not self.api_key:
            return "Error: Resend API key not configured."

        # HTML-escape body to prevent injection, then restore newlines as <br>
        safe_body = html.escape(body).replace("\n", "<br>")
        safe_subject = html.escape(subject)

        html_content = f"""
        <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.8; color: #333; max-width: 700px; margin: auto; padding: 24px;">
            <h2 style="color: #1a73e8; border-bottom: 2px solid #1a73e8; padding-bottom: 8px;">{safe_subject}</h2>
            <div style="font-size: 15px;">{safe_body}</div>
            <hr style="margin-top: 32px; border: none; border-top: 1px solid #eee;">
            <p style="color: #888; font-size: 12px;">Generated by AI Travel Guide Agent &mdash; powered by ReAct</p>
        </body>
        </html>
        """
        url = "https://api.resend.com/emails"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "from": _get_from_email(),
            "to": [to],
            "subject": subject,
            "html": html_content,
        }
        try:
            response = requests.post(url, headers=headers, json=payload, timeout=15)
        except requests.exceptions.Timeout:
            return "Error: Email request timed out."
        except Exception as e:
            return f"Error sending email: {e}"

        if response.status_code not in [200, 201]:
            try:
                err = response.json().get("message") or response.json().get("name") or "Unknown error"
            except Exception:
                err = f"HTTP {response.status_code}"
            return f"Error: Email delivery failed — {err}"

        data = response.json()
        return f"Email sent successfully!\nEmail ID: {data.get('id')}"
